name: Dispatch Event

on:
  push:
  pull_request:
    types: [opened]

jobs:
  run_deployment:
    env:
      GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - name: Docker
        run: |
          docker image pull node@sha256:01627afeb110b3054ba4a1405541ca095c8bfca1cb6f2be9479c767a2711879e
          docker image inspect node@sha256:01627afeb110b3054ba4a1405541ca095c8bfca1cb6f2be9479c767a2711879e
      - name: Dispatch Via Curl
        run: |
          curl -H "Authorization: token $GH_TOKEN" \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          "https://api.github.com/repos/jonparker/smoke-test/dispatches" \
          -d '{"event_type": "run-smoke-test", "client_payload": {"env": "acceptance", "release": "1.2", "deployment_id": "3"}}'
      - name: Dispatch Event to Other Repo
        uses: actions/github-script@v4
        with:
          script: |
            const { Octokit } = require("@octokit/rest");
            const octokit = new Octokit({
              auth: process.env.GITHUB_TOKEN
            });

            await octokit.request('POST /repos/:owner/:repo/dispatches', {
              owner: 'jonparker',
              repo: 'smoke-test',
              event_type: 'run-smoke-test',
              client_payload: {
                env: 'acceptance',
                release: '1.2',
                deployment_id: '3'
              }
            })
